### ISSUE TITLE
Certain lines need to be customize-able for public

### ISSUE THREAD

**Issue by swilkey** [newtribesmission/NTM-WPMem-Email-As-Username#3]
Hi Stephen,
I understand that you wrote this for New Tribes Mission, but it seems to be hardcoded to say "Email (Use your mission email address if applicable)" which makes it a bit weird for the rest of us when we use it.  For now I've edited your php code directly but if you upgrade the plugin then it will overwrite my change.  Is there a way you can make this message configurable?
I also note that there is a redirect in there to /missionary-services.  In my context it would be very bad if this appeared - I'm not sure what circumstances would cause it.  Is there a way to remove that also?

**Comment by stevish-com** [comment]
Ah yes, an options page would be wonderful for this plugin, wouldn't it? Part of the requirements for this plugin (for New Tribes Mission) was simplicity and timelessness. It uses the most general hooks possible and is designed to survive for as long as possible without requiring an upgrade. Options pages tend to require more hooks and therefore more stuff to break.

However, my other plugin for NTM does utilize an options age because it was necessary to update options regularly. I may be able to copy that code in such a way that if one breaks, they both break, meaning it's the same fix for both plugins. That wouldn't increase the workload by too much...

I'll look into this when I get time. Thanks for pointing it out. If you have time, it would be helpful for someone to go through and make a list of things that would need to be made into options. And it would be even MORE helpful if that someone even looked at the code and mentioned what line the option would be called from (i.e. "Email (Use your mission email address if applicable)", line 51).

**Comment by swilkey** [comment]
Hi Stephen,

Thanks for responding so quickly.  This is what I could find:
51 - Email (Use your mission email address if applicable)
146 - redirection to /missionary-services homepage after a user deletes their own account
160 - redirection to /missionary-services/profile page when a non-admin tries to access an admin page

That's all I could find that would need the ability for people to be able to change.  The rest seems very straightforward and unnecessary to alter.

Thanks for all your work on this plugin and being willing to share it with the rest of us!

**Comment by stevish-com** [comment]
You're welcome. I'm not sure when I will have time to work on this. I've
been quite busy, and this feature adds nothing to our core installation.
The only reason this plugin is public is because it's just as easy for me
to make it available to everyone as it is to just us. For now you'll
probably have to stick with editing the code and trusting that I won't
release too many updates (which is the plan).

As a compromise, on my next release I will at least make all three of those
things into variables declared at the top of the file. It will still
require editing the plugin file after every update, but it should make the
process easy, especially with moving line numbers.

Also, I'll leave this issue open as a reminder to implement this if/when
it's expedient for me to do so. It'll probably have to be on my own time.

**Comment by stevish-com** [comment]
The variables have been added to the code. I have not pushed a release yet though... forcing the update would defeat the purpose of this band-aid. However, if I release any other changes in the future, this is already done, so it should be easy to re-customize the code.

**Comment by swilkey** [comment]
Brilliant.  Thanks so much Stephen

**Comment by stevish-com** [comment]
So, lloc was kind enough to add an options page (among other things) and his code loks pretty simple and timeless, so I've added it in. I also pushed the update to the WP repository. If you update now, you can add your custom redirects to the options page. You'll have to do something with a language file in order to change the "Email (Use your mission email address if applicable)" thing though... I'm not sure exactly how that works, I've not done a lot with language files. If you figure it out, feel free to let me know.

**Comment by swilkey** [comment]
Thanks!

**Comment by lloc** [comment]
You could just copy the file ntmeau-it_IT.po to ntmeau-fr_FR.po for example and open it with poEdit. It will create the .mo file when you save your work.
