### ISSUE TITLE
Allow users change email

### ISSUE THREAD

**Issue by mauriciogofas** [newtribesmission/NTM-WPMem-Email-As-Username#4]
Hello! 
How do I allow users to change their email? 

Even before using wp-members I've allowed users do login with email, so the first registered email can keep being username they will never know what your real username.

Thanks in advance!

**Comment by stevish-com** [comment]
This is definitely by design, so I won't be changing it in the plugin, but you can change it in your own installation. Currently, the best way to do this would be to comment out (add a // before) line 182 (well, it's on line 182 for now) of email-as-username-for-wp-members.php. The line looks like this:

`add_action('init','ntmeau_block_admin_pages_for_subscribers',0);`

and you want it to look like this:

`//add_action('init','ntmeau_block_admin_pages_for_subscribers',0);`
